tinyalsa/tinyalsa

- mixer.c
- tinymix.c
updates series with tab space as 4
> Tlv support2

- Android.mk
- tinywavinfo.c
-This utility displays average power of each channel in the wave file.
-This utility quickly checks the audio input path is up or not by analysing wav file captured by tinycap
Signed-off-by: Jaydeep Dhole <jaydeepdhole@gmail.com>
> Added tinywavinfo utility

- include/tinyalsa/asoundlib.h
- pcm.c
This branch/pull request contains few new apis for tinyalsa
- pcm_delay() for reporting the pcm delay value
- pcm_get_subdevice() for reporting the subdevice for device
- allow pcm_wait to work for POLLIN too
> Wait delay

- mixer.c
Each mixer_ctl has an associated snd_ctl_elem_info, which was
kept in a separate array with pointers from the mixer_ctl to
its corresponding snd_ctl_elem_info. This means double
pointer dereferences when looking up the info. It also means
extra work to add support for extending the arrays to include
dynamically added controls because the pointers from the ctl
array to the info array would have to be updated.
This patch removes the info list and gives each mixer_ctl struct
its own local snd_ctl_elem_info, removing the additional pointer
dereferencing.
> mixer: remove separate info list

- tinyplay.c
-Added raw file support in tinyplay to play PCM raw files
Signed-off-by: Jaydeep Dhole <jaydeepdhole@gmail.com>
> Added raw file support in tinyplay

- mixer.c
- tinycap.c
- tinymix.c
- tinypcminfo.c
- tinywavinfo.c
There are other warnings and [Clang Static Analyzer](http://clang-analyzer.llvm.org/) also found some warnings.
> fix some cppcheck warnings

- Makefile
A few changes:
* Don't hardcode 'gcc' and use $(CC) instead
* Split off CFLAGS/LDFLAGS so we can pick them up from the environment
* Add a static library build
> build: Redo Makefile a bit

- tinycap.c
Signed-off-by: Viraj Karandikar <vkarandikar@nvidia.com>
> tinycap: add capture time parameter

- mixer.c
Signed-off-by: Ben Zhang <benzh@google.com>
> mixer: check for overflow and NULL return

- utils/tinymix.c
I work on platforms based on the Qualcomm SnapDragon chip. There can be hundreds of paths on the audio side of this chip.
There was a recent change whereby tinymix will ALWAYS prints the routes/paths
for the different ports on ALSA. I consider this to be a regression. It
really should only be printed if asked.
In addition, I've modified tinymix to more closely conform to the following:
https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html
Lastly, I removed a redundant errno.h..
In modifying the code, I've tried to follow the principal of least deviation from previous behavior.
>  tinymix shouldn't always print the paths 

- include/tinyalsa/mixer.h
- src/mixer.c
Hi,
pull request #47 is long time pending.
https://github.com/tinyalsa/tinyalsa/pull/47
I incorporated review comments and reworked on the patches mentioned on above link.
Will you please get this merged now. Kindly let me know if anything needs to be modified.
Thanks,
Pankaj
> Tinyalsa: Add support to poll on alsa control

- debian/control
- debian/rules
Separate package with debug symbols for a library.
> Debian debug package

- utils/tinyplay.c
A really minor change that has a fair amount of utility for my own random hackery. Passing data in through a FIFO also worked as well, but this is a bit more direct, and the required modifications are very light.
> Added reading from stdin.

- utils/tinycap.c
> Fixed potential risk of wild pointer

- src/mixer.c
- utils/tinymix.c
Some changes to make the reading of enum controls slightly more efficient and to tidy up the output format produced by them.
> Minor tweaks to enum controls

- utils/tinymix.c
Signed-off-by: Andrew Ford <aford@opensource.cirrus.com>
> tinymix: fix use of -D with set command

- src/pcm.c
This allows starting capture from another thread.
See the commit 932a81519572 ("ALSA: pcm: Comment why read
blocks when PCM is not running") in Linux kernel.
> pcm: Allow to wait if capture is not running

- Android.bp
- CMakeLists.txt
- examples/Makefile
- include/tinyalsa/plugin.h
- meson.build
- src/Makefile
- src/mixer.c
- src/mixer_hw.c
- src/mixer_io.h
- src/mixer_plugin.c
- src/pcm.c
- src/pcm_hw.c
- src/pcm_io.h
- src/pcm_plugin.c
- src/snd_card_plugin.c
- src/snd_card_plugin.h
- utils/Makefile
These are initial set of patches to add the support for plugins to tinyalsa. Changes are to add PCM plugin support, perform several tasks for plugin (ex: hardware parameters validation, etc) such that plugin development is easier. Also add changes to support mixer control plugins. The mixer concept is split into groups, one for the hardware group and another for the virtual group.
Please review the Issue and the code changes and recommend any changes to either code/design, etc and I will work on absorbing them
This pull request corresponds to #135
> Plugin support

- examples/Makefile
- utils/Makefile
Cross-compilation failing due to make library resolution. Fixes #145
----
#
> Fix cross-compilation

- src/pcm.c
It would result in a double free:
$ tinyplay example.wav
failed to open for pcm 0,0
*** glibc detected *** ./utils/tinyplay: double free or corruption (fasttop): 0x402dc258 ***
Aborted
$
The crash happens here:
Program received signal SIGABRT, Aborted.
0x40070e78 in raise () from /lib/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.16-34.olpc.0.fc18.armv7hl libgcc-4.7.2-8.fc18.armv7hl
(gdb) bt
#0  0x40070e78 in raise () from /lib/libc.so.6
#1  0x400724b8 in abort () from /lib/libc.so.6
#2  0x400ad6e0 in ?? () from /lib/libc.so.6
#3  0x400b54e8 in ?? () from /lib/libc.so.6
#4  0x2a00486c in pcm_hw_close ()
#5  0x2a0032e0 in pcm_close ()
#6  0x2a0016b0 in ctx_init ()
#7  0x2a000c98 in main ()
(gdb)
The previous free was done here:
Breakpoint 1, 0x400b8b8c in free () …
> pcm: avoid calling pcm_hw->close() twice

- utils/tinywavinfo.c
This fixes multiple -Wunused-result warnings that are present, at least with clang.
> tinywavinfo: add wrapper for fread to check its return value

- include/tinyalsa/mixer.h
WIP with reference to issue #175
> Minor TLV Fixes

- src/mixer.c
- utils/tinymix.c
As discussed in https://github.com/tinyalsa/tinyalsa/issues/171 , tinymix utility adds tlv header and calls mixer_ctl_set/get_array which again adds tlv header which is incorrect. This PR fixes it by introducing mixer_ctl_get_byte_array() and mixer_ctl_set_byte_array() which does not adds tlv header
> Fix mixer set/get for tlv based controls

- debian/changelog
This should also fix the version check in scripts/travis-build.sh
> Add changelog for tinyalsa 2.0.0

- .gitignore
- BUILD
- README.md
- WORKSPACE
- tests/include/pcm_test_device.h
- tests/src/mixer_test.cc
- tests/src/pcm_in_test.cc
- tests/src/pcm_loopback_test.cc
- tests/src/pcm_out_test.cc
- tests/src/pcm_params_test.cc
- tests/src/pcm_test.cc
The total coverages of these tests are 46.2% for lines and 63.5% for functions. The lines and functions for plugin feature are counted as well, but we don't have any plugin implementation. Therefore, no test tests that part of code.
> Tests for libtinyalsa

- src/pcm.c
1. Remove calculation of boundary and retrieve boundary from ALSA
kernel. Also fix type when getting available and advance appl_ptr.
2. Fix avail in pcm_mmap_transfer getting overflow.
3. Fix typo.
> match the boundary type with kernel driver

- include/tinyalsa/pcm.h
- include/tinyalsa/plugin.h
- src/pcm.c
- src/pcm_plugin.c
Support pcm_drain in pcm_hw and pcm_plugin.
> Support pcm drain ops

- CMakeLists.txt
- src/pcm_plugin.c
- utils/tinywavinfo.c
This is a follow up for PR https://github.com/tinyalsa/tinyalsa/pull/260. 
The commit history for the old PR is messed up during force push and commit history reorder
> Fixes bugs and warnings 

- src/pcm.c
Fix mmap wait timeout issue. if there is no enough room to write, wait the time according to avail_min.
> pcm: fix for mmap usecase

- include/tinyalsa/pcm.h
- src/mixer.c
- src/pcm.c
While packaging for Debian, I thought it'd be nice to fix some typos I found. :)
> Fixes for some typos

- utils/tinycap.c
if pcm_readi returns an error ( < 0 ) tinycap sigfaults.  This patch handles that case.
> handle pcm_readi error case
