tinypcminfo.c

When building tinyalsa with gcc 5.x, the following warnings appear:
tinypcminfo.c:97:52: warning: 'format_lookup' is static but used in inline function 'pcm_get_format_name' which is not static
return bit_index < ARRAY_SIZE(format_lookup) ? format_lookup[bit_index] : NULL;
^
tinypcminfo.c:97:35: warning: 'format_lookup' is static but used in inline function 'pcm_get_format_name' which is not static
return bit_index < ARRAY_SIZE(format_lookup) ? format_lookup[bit_index] : NULL;
And the build fails with:
tinypcminfo.o: In function `main':
tinypcminfo.c:(.text+0x2f0): undefined reference to `pcm_get_format_name'
collect2: error: ld returned 1 exit status
To fix this, this patch marks the pcm_get_format_name() as static,
since it's anyway only used in tinypcminfo.c.
Signed-off-by: Thomas …

tinypcminfo: make function pcm_get_format_name() static

---

tinycap.c
tinyplay.c

sw_params ioctl() is failing with 'invalid parameter' error
since pointer to pcm_config passed from tinyplay is not zero
initialized, hence invalid values are passed for some
parameters.
authored-by: Shiv Maliyappanahalli <smaliyap@codeaurora.org>
Bug: 23525433
Change-Id: I841f29c82ec3fb7646ad8c47fca25963b5f77945

initialize pcm_config to zero

---

pcm.c

avail will be wrong when avail is same with pcm->boundary.

avail issue

---

include/tinyalsa/asoundlib.h
mixer.c

Add a function to get an id of a control that can be
passed to mixer_get_ctl(). This can be used to lookup
a control by name and store its id for later use rather
than have the overhead of name lookup each time it is
used. Lookup by id is quick and avoids the disadvantage
that storing a pointer to the mixer_ctl object creates
a client with a dependency on the address of the internal
control array.
Signed-off-by: Richard Fitzgerald <rf@opensource.wolfsonmicro.com>

mixer: Add mixer_ctl_get_id

---

include/sound/asound.h

without including it, we get
In file included from mixer.c:44:0:
include/sound/asound.h:337:18: error: field 'trigger_tstamp' has incomplete type
include/sound/asound.h:338:18: error: field 'tstamp' has incomplete type
etc.
note that time.h is included first so linux' libc-compat.h can kick in and prevent userspace/kernel header collisions.
using ```<linux/time.h>``` instead of ```<time.h>``` leads to said problems:
```
gcc -c -fPIC -Wall mixer.c -Iinclude
In file included from /usr/include/sys/select.h:16:0,
from /usr/include/sys/time.h:9,
from include/tinyalsa/asoundlib.h:32,
from mixer.c:46:
/usr/include/bits/alltypes.h:265:8: error: redefinition of 'struct timeval'
```

asound.h: include <time.h> to get struct timespec prototype

---

mixer.c
pcm.c

In some old (2.6.32.x) kernel headers, asound.h does not include linux time.h
when __KERNEL__ is undefined, which may break userspace.
The build failures caused by this are similar to those fixed by c8333f8c.
Signed-off-by: Dima Krasner <dima@dimakrasner.com>

include time.h, to prevent use of struct timespec before definition

---

include/tinyalsa/asoundlib.h
mixer.c

Control names are not unique and can be shared by multiple mixers controls.
When this happens, there is no way of accessing the mixer using its control
name, because mixer_get_ctl_by_name() always returns the first match. The only
way of accessing the mixer is through its control number, i.e. using
mixer_get_ctl().
This patch adds the function mixer_get_ctl_by_name_and_index() to offer the
possibility to retrieve a control through its name and index.  This index
corresponds to the nth occurence of the control name in the global supported
controls names list.
Change-Id: Ie29bf2a949ecf69f106bbe359155cdbfbe98928c
Signed-off-by: Frédéric Boisnard <fredericx.boisnard@intel.com>
Signed-off-by: David Wagner <david.wagner@intel.com>
Signed-off-by: Bruce Beare <bruce.j.beare@intel.com> …

Add a function to disambiguate duplicate control names

---

mixer.c

Currently, all information about all mixers are fetched during mixer_open().
For enum mixers, an additional step gets the string for each enumerated value -
this can lead to a lot of ioctls and take time even when these mixers aren't
used afterward.
Defer fetching integer/string mapping values when needed (when getting/setting
a enum mixer).
Signed-off-by: David Coutherut <davidx.coutherut@intel.com>
Signed-off-by: David Wagner <david.wagner@intel.com>
Author-Tracking-BZ: 113043

Defer filling enum-type mixers information

---

src/mixer.c
src/pcm.c

If users want to use only **pcm.c** or **mixer.c** they can, right?
Is it necessary to include _tinyalsa/asoundlib.h_ given that **mixer.c** doesn't use **pcm.h** and **pcm.c** doesn't use **mixer.h**.

We can include only necessary headers!?

---

doxygen/Makefile

On some machine doxygen is not available, instead of having the build
error out, display a warning message to the user.
Signed-off-by: Maxime Hadjinlian <maxime.hadjinlian@gmail.com>

doxygen/Makefile: test if doxygen is available

---

.travis.yml

Travis CI is a CI service, free to use for open-source projects. It can automatically build any incoming Pull Request and catch build errors provided that the project's administrator activates Travis CI on the repository.
See https://travis-ci.org https://docs.travis-ci.com

Add a Travis CI configuration file

---

doxygen/Makefile

The name of man pages was incorrect. Also, using the coreutils'
"install" command makes sense when installing files.
Signed-off-by: David Wagner <david.wagner@intel.com>

Fix the installation of manpages

---

Makefile
src/Makefile

They were installed under $prefix/ instead of $prefix/tinyalsa/

Fix install path of include files

---

include/tinyalsa/mixer.h
src/mixer.c

New controls could appear during runtime, for example if a
new firmware is downloaded to a DSP. Since ALSA drivers are
not supposed to delete or renumber existing controls we can
assume that any new controls will be after any controls we
already know about. We can use this to enable extending our
current list of controls, which is more efficient than
closing the mixer session and recreating it.
Signed-off-by: Richard Fitzgerald <rf@opensource.wolfsonmicro.com>

mixer: add ability to update control list with new controls

---

include/tinyalsa/pcm.h

As we may see in <http://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html>, the **XRUN** state
takes place when _"The PCM device reached **overrun (capture)** or **underrun (playback)**."_

pcm.h -- (over/under)run definition

---

src/mixer.c

The @return comment description incorrect.
Fix it.
Change-Id: I148a5ebf3e05eb4824beb4c8fa1032a38272d86d
Signed-off-by: Pankaj Bharadiya <pankaj.laxminarayan.bharadiya@intel.com>

Fix mixer_wait_event function comments

---

utils/tinymix.c

The arguments passed after the set command are not handled properly,
leading to segfaults or inability to set controls
Example with control 0 which is Headset Volume on my NUC:
before fix
$ ./tinymix set 0
Segmentation fault
$ ./tinymix set 0 10
Segmentation fault
$ ./tinymix set 0 10 20
Error: 3 values given, but control only takes 2
After correction
$ ./tinymix set 0
no value(s) specified
$ ./tinymix set 0 10
$ ./tinymix set 0 10 10
$ ./tinymix set 0 10 10 10
Error: 3 values given, but control only takes 2
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

tinymix: fix segfaults with set command

---

utils/tinyplay.c

pcm_writei expects size of data in frames, whereas currently size
is passed as number of bytes. So convert number of bytes to frames
for argument to pcm_writei.
Signed-off-by: Jaikrishna Nemallapudi <jaikrishnax.nemallapudi@intel.com>
Signed-off-by: Subhransu S. Prusty <subhransu.s.prusty@intel.com>

Fix to pass num_frames to pcm_writei

---

include/tinyalsa/interval.h

The ssize_t type requires the unistd.h header. This fixes build with musl
libc:
In file included from ../include/tinyalsa/limits.h:32:0,
from limits.c:1:
../include/tinyalsa/interval.h:38:2: error: unknown type name 'ssize_t'
ssize_t max;
^
Signed-off-by: Baruch Siach <baruch@tkos.co.il>

interval.h: add missing header

---

meson.build
version.py

- Extract project version from `tinyalsa/version.h` for easier maintainability
- Version shared lib: tinyalsa.so -> tinyalsa.so.1.1.1

meson: extract project version from header file and version .so

---

include/tinyalsa/pcm.h
src/pcm.c

Please review this in my fork. In pull requests GitHub reorder commits based on author date.

Fix behaviors, remove 'prepared' and 'running' variables

---

src/mixer.c

Fixes #71 
Changed order of operations to preserve the precision during the division.

Fix integer division issue in int_to_percent function

---

src/pcm.c

SUBFORMAT is always zero.
SAMPLE_BITS and FRAME_BITS are refined by ALSA based on the
already set FORMAT and CHANNELS.

pcm: Remove setting unnecessary parameters

---

CMakeLists.txt

Helps fix build/packaging issues on machines where default libdir is not
lib but say lib64
Signed-off-by: Khem Raj <raj.khem@gmail.com>

Use CMAKE_INSTALL_<path> instead of hardcoding bin/lib/ install paths

---

src/pcm.c

Using MMAP APIs, this parameter wake up application
when 'avail_min' samples are availables.
When audio processing expects exactly a full period size samples,
the default parameter to 1 burns CPU until the full period available.
Fix SW params.avail parameter to period size value.
Signed-off-by: Miguel GAIO <mgaio35@gmail.com>

pcm: Set SW params.avail_min to period size

---

src/pcm.c

sterror() surely doesn't appreciate that:
cannot set hw params: Unknown error -22
where it should've been:
cannot set hw params: Invalid argument

pcm: do not negate errno

---

Makefile

Export plugin.h so that it can be used by tinyalsa
clients.
Signed-off-by: Rohit kumar <rohitkr@codeaurora.org>

tinyalsa: add plugin.h to install path

---

src/pcm.c
src/pcm_hw.c

Prevent the call to pcm->ops-close() if pcm->ops->open() fail.
Fix memory leak in pcm_hw_open() in case of failure.
* thread #1, name = 'ut', stop reason = signal SIGSEGV: invalid address (fault address: 0x8)
frame #0: 0x00007ffff7f863e8 libtinyalsa.so.1`pcm_hw_close(data=0x0000000000000000) at pcm_hw.c:61:21
58  	{
59  	    struct pcm_hw_data *hw_data = data;
60
-> 61  	    if (hw_data->fd > 0)
62  	        close(hw_data->fd);
63
64  	    free(hw_data);
(lldb) bt
* thread #1, name = 'ut', stop reason = signal SIGSEGV: invalid address (fault address: 0x8)
* frame #0: 0x00007ffff7f863e8 libtinyalsa.so.1`pcm_hw_close(data=0x0000000000000000) at pcm_hw.c:61:21
frame #1: 0x00007ffff7f8491c libtinyalsa.so.1`pcm_close(pcm=0x0000000000a9eba0) at pcm.c:820:5
frame #2: 0x00007ffff7f84e0a …

pcm_hw_close: avoid SIGSEGV when pcm_hw_open fail

---

include/tinyalsa/plugin.h

ssize_t is defined in <sys/types.h>, see
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html
Add an include for it to avoid a compile error when building with musl:
```
../include/tinyalsa/plugin.h:184:5: error: expected specifier-qualifier-list before 'ssize_t'
184 |     ssize_t (*read_event) (struct mixer_plugin *plugin,
|     ^~~~~~~
```

tinyalsa: include <sys/types.h> for ssize_t

---

src/mixer_plugin.c

memcpy() is arguably wrong when copying these string constants.
The string constants will usually just be as long as necessary,
so we might copy some random memory behind it and eventually crash.
Use strncpy() instead to avoid copying characters after the null
terminator. For some reason the strings in snd_ctl_card_info use
unsigned chars, so we need a cast to char* to make it compile
unfortunately...
This fixes the following compile error on ppc64le:
```
In function 'mixer_plug_get_card_info',
inlined from 'mixer_plug_ioctl' at mixer_plugin.c:371:15:
mixer_plugin.c:333:5: error: 'memcpy' forming offset [9, 16] is out of the bounds [0, 8] [-Werror=array-bounds]
333 |     memcpy(card_info->id, "card_id", sizeof(card_info->id));
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```

tinyalsa: use strncpy instead of memcpy to copy string constant

---

scripts/version.sh

Change shebang to #!/bin/sh.
Remove usage of non-POSIX 'local' builtin, and replace it with using a
function's positional parameters to store variables, as they are local
to the function.

scripts/version.sh: switch from bash to POSIX sh

---

src/pcm.c

MAP_FILE is a non-standard mmap flag, and has no effect on conformant
systems.

src/pcm.c: remove MAP_FILE mmap flag

---

include/tinyalsa/mixer.h
src/mixer.c
src/mixer_hw.c
src/mixer_plugin.c

The PR consists of 3 changes:
1) Add mixer_consume_event() API: This was earlier introduced in google-origin branch. Change is directly ported from there (https://github.com/tinyalsa/tinyalsa/commit/b570106d92d72c4275f38f69723376af5db1e585 ).
2) Add mixer_read_event() and plugin support for mixer_consume_event() and mixer_read_event(). mixer_consume_event() just used to clear the event. However, there was no API to provide event details to the client. mixer_read_event() is updated version of mixer_consume_event() where the client can get the event details. This helps when the client polls for mixer event and receives multiple events. mixer_read_event() read and clear one event at a time. With this, plugin support for mixer_read_event() and mixer_consume_event() is also added.
3) Fix …

Mixer event plugin update

---

utils/optparse.h
utils/tinycap.c
utils/tinymix.c
utils/tinypcminfo.c
utils/tinyplay.c

https://github.com/skeeto/optparse
This allows option parsing to be done in a much cleaner way than the manual method done by most of the utilities, and removes the need for the GNU-extension getopt_long (only used in tinymix).

Add public domain header-only option-parsing library optparse

---

CMakeLists.txt

Use scripts/version.sh, and set version in project() using its output.
Instead of using a variable to store the definition of
TINYALSA_USES_PLUGINS, and adding it as a compile option, use a
generator expression to define it in target_compile_definitions when the
option is enabled.
Set BUILD_SHARED_LIBS to on by default.
Add options to disable examples and utils.
Instead of using SRCS and HDRS variables, set PUBLIC_HEADER property on
tinyalsa to install the headers along with the target.
Set library version, so the shared library will have version suffixes.
Check that C warning flags are supported instead of adding them
unconditionally.
Use ${CMAKE_DL_LIBS} instead of hardcoding "dl", and add it to
tinyalsa's link interface and link depends, instead of linking it in the
examples and utils. …

Various cmake improvements

---

CMakeLists.txt
include/tinyalsa/plugin.h
src/snd_card_plugin.c

Set standard to c99, require it, disable language extensions.
Define _POSIX_C_SOURCE to 200809L so time.h declares struct timespec.
Add -Wpedantic to find use of language extensions.
snd_card_plugin.c: remove one unnecessary ';' to make -Wpedantic work
This will prevent accidental usage of non-standard functions from the standard headers, and prevent use of language extensions. This won't prevent the use of needed linux-specific functions/types/macros from linux headers, such as sound/asound.h, as they don't gate things based on feature test macros like standard headers do.

cmake: specify c99

---

CMakeLists.txt

Currently the `CMake` build fails if we disable building the utils.
```
CMake Error at CMakeLists.txt:72 (target_link_libraries):
Cannot specify link libraries for target "tinywavinfo" which is not built
by this project.
```

Fix error when building with -DTINYALSA_BUILD_UTILS=OFF

---

examples/pcm-writei.c

per pcm_writei: On success, this function returns the number of frames written; otherwise, a negative number.

Fix pcm-write example

---

utils/tinyplay.c

1. Use the period size as write buffer size to avoid underrun.
2. Calculate the thresholds again after the options parsing.

Fix tinyplay bugs

---

src/pcm.c

Current return value of pcm_write()/pcm_read()
comes from pcm_writei()/pcm_readi() which is the
actual frames written/read. But the old pcm_write()
/pcm_read() just returns 0 on success and a nagative
value on error.
This change will keep the pcm_write()/pcm_read() as
the old behavior which has been already used by
many applications, and is also matching the comment
above each function.
Signed-off-by: Kui Wang <wangkuisuper@hotmail.com>

Backward compatible for pcm_write() pcm_read()

---

include/tinyalsa/attributes.h
include/tinyalsa/mixer.h
include/tinyalsa/pcm.h
src/mixer.c
src/pcm.c

1. Add a missing field and a function
2. Disable the deprecated attribute in Android temporarily to allow us to use "pcm_read/write" which are deprecated upstream
3. Remove an unused define and an include in mixer.h
4. Add mixer_ctl_event and copy the snd_ctl_event to mixer_ctl_event
5. Add pcm_ioctl function and mark as deprecated function

fix build breakage in Android

---

Android.bp

https://android.googlesource.com/platform/external/tinyalsa_new/+/535e6ea3edcb6e119d465073facc3b2a338bdcb1
[LSC] Add LOCAL_LICENSE_KINDS to external/tinyalsa_new
Added SPDX-license-identifier-BSD SPDX-license-identifier-Unlicense to:
Android.bp
Bug: 68860345
Bug: 151177513
Bug: 151953481
Test: m all
Exempt-From-Owner-Approval: janitorial work
Change-Id: I21fe326f57f35b252901cf1423c4af149694fb51

Sync AOSP: [LSC] Add LOCAL_LICENSE_KINDS to external/tinyalsa_new

---

src/mixer.c
src/pcm.c
tests/src/mixer_test.cc

For the compatibility with version 1.x, do pcm_prepare before starting the pcm driver.

Fix compatible issue and refine null parameters checking 

---

src/pcm_hw.c
tests/include/pcm_test_device.h
tests/src/pcm_loopback_test.cc
tests/src/pcm_test.cc

When a client opens a PCM device whose substreams are all occupied without the non-blocking flag, the open function would be blocked in the kernel until the previous opened ones are closed. This would cause deadlock if they try to hold the same lock. Most of the ALSA PCM drivers on embedded systems are implemented with the ALSA SOC framework. Each PCM device has only one substream. This problem would happen frequently. To force pcm_open to open PCM devices with non-blocking flag is beneficial to resolve this problem. It returns the control to clients to try again later.
The reason why we don't call pcm_open with PCM_NONBLOCK is that the PCM_NONBLOCK also affects the read and write behaviors.
I also add a test case to test whether the pcm_open would be blocked.

force pcm_open to open device with the non-blocking flag

---

src/pcm_hw.c

The pcm_hw_close refused to close the zero fd. Remove the condition to close the zero fd.

fix the zero fd closing problem

---

include/tinyalsa/meson.build

This adds the missing public headers that are installed with the tinyalsa CMake target that is set in `CMakeLists.txt`.  
Working as expected, tested while packaging tinyalsa as an Arch Linux package.
Closes #215.

meson: add attributes.h and plugin.h public headers

---

src/mixer.c

In mixer_get_ctl_by_name_and_index(), the post-fix decrement means that the index will be decremented after the comparison, but before the return, leading to an unsigned integer underflow.
The error is caught on Android platforms, presumably using `-fsanitize=integer`. When built without the option the underflow would still occur but given the function returns immediately afterwards there would be no side effects.

mixer: fix index underflow when index=0

---

src/mixer_plugin.c
src/pcm_plugin.c

Since gcc 9.0, checking strncpy is more strict.
Please refer https://github.com/tinyalsa/tinyalsa/issues/219.

fix strncpy warnings

---

src/mixer_plugin.c
src/pcm_plugin.c

Sorry for my previous imcomplete PR.https://github.com/tinyalsa/tinyalsa/pull/220
I think strncpy in tinyalsa has potential bug.
(please refer  https://stackoverflow.com/questions/21210293/problems-with-strncpy-and-how-to-fix-it)
This PR is to insert null at end of strncpy target array.

fix strncpy potential bug

---

WORKSPACE
include/tinyalsa/pcm.h
src/mixer.c

1. Since unsigned int and unsigned long are 4 and 8 bytes on LP64 machine, respectively, the type mismatching causes problems when setting up. Fix the type mismatching between pcm_config and snd_pcm_sw_params.
2. Add the missing ioctl to get the IEC958 data.
3. Fix the branch name of googletest.

Fix a type issue and a mixer control issue.

---

src/mixer.c
src/mixer_hw.c
src/pcm_hw.c
src/pcm_plugin.c

Include time.h before asound.h to avoid the following build failure on musl that was already fixed a long time with tinyalsa@c8333f8 but reappeared on version 2.0.0:
```
In file included from ../src/pcm_hw.c:42:
/home/peko/autobuild/instance-1/output-1/host/i586-buildroot-linux-musl/sysroot/usr/include/sound/asound.h:444:18: error: field 'trigger_tstamp' has incomplete type
444 |  struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
|                  ^~~~~~~~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/a75e23dc585bd071f4d65face5489ed6ac22edbe
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

include time.h before asound.h

---

utils/tinywavinfo.c

The main analysis loop of utility tinywavinfo.c reads too far in memory pass the buffer end. Adding "/bytes_per_sample" to the for-loop end condition seemed to fix this bug.

Fixed bug with main analysis loop

---

utils/tinycap.1
utils/tinycap.c

This pull request implements mmap (-M option) support in the tinycap utility. This is necessary for some hardware to work (e.g. Plugable HDMI capture card with USB ID 1bcf:2c99). This patch is simple, it just enables PCM_MMAP flag for pcm_open() function in libtinyalsa, the actual functionality is already implemented in the library. My testing has confirmed that it does work with the aforementioned hardware after applying the patch.

mmap support in tinycap

---

utils/tinyplay.c

The bits-to-format function returned bool, which happened to work for PCM_FORMAT_S16_LE (0) and PCM_FORMAT_S32_LE (1). However, all other formats were incorrectly mapped to PCM_FORMAT_S32_LE. Return enum pcm_format instead.

tinyplay: fix playback of 24-bit and 8-bit pcm

---

include/tinyalsa/mixer.h
src/mixer.c
utils/tinymix.c

There can be multiple chmap mixer control in a platform (e.g. - Playback Channel map / Capture Channel map) for each pcm devices. Tinyalsa does not provide an api to get the mixer_ctl handle based on combination of mixer control name and pcm_device id. This adds support for getting mixer_ctl handle for such cases.

Chmap mixer support

---

src/pcm.c

Add plugin support for pcm_ioctl according to the define TINYALSA_USES_PLUGINS

pcm: Replace ioctl() with pcm->ops->ioctl()

---

include/tinyalsa/plugin.h
src/mixer_plugin.c

Corner case observed when new event coming just after old events read, eventfd counter is reset to 0 due to old event reading even though a new event just increase eventfd counter by 1. This will cause delay of event notification.
Use flag EFD_SEMAPHORE when creating eventfd to decrease eventfd counter by actual event numbers getting read.

fix race condition between plugin event read/write
